### PR TITLE
Rewrite type inference system

### PR DESCRIPTION
**Pull request by Runemoro**
With the new system, there's almost perfect type inference except for some unchecked casts and some lambdas. Test it on Minecraft or DataFixerUpper (which is full of generics) to see the difference.

Here are some test cases that the new inference system can infer correctly but not the old one: https://gist.github.com/Runemoro/86852cdb80f8ffed54f066fe14522530

### CODE REVIEW

**Comment by asiekierka** [comment]
Please consider sending the same PR to upstream!

**Review by liach — APPROVED** [review]

**Comment by Runemoro** [comment]
https://bitbucket.org/mstrobel/procyon/pull-requests/22/rewrite-type-inference-system

**Comment by liach** [comment]
Hmm, i thought the original procyon was dead... :heart: on this pr

**Review by modmuss50 — APPROVED** [review]
im happy to merge this now, we can pull in upstream changes once this and possibly other things have changed.

**Pull request merged**
