### PR TITLE
Fix enigma not recognizing method name in method references

### PR DESCRIPTION
**Pull request by liach**
Signed-off-by: liach <liach@users.noreply.github.com>

After applying the patch in enigma manually:
image

### CODE REVIEW

**Review by Gegy — APPROVED** [review]
Nice!

**Comment by JamiesWhiteShirt** [comment]
Will you submit this upstream?

**Comment by liach** [comment]
Apparently I need a different fix for upstream. I got one but turns out I cannot submit merge request on bitbucket, so whatsoever. https://bitbucket.org/liach/procyon/commits/48ddd6274e8e6b0a4bf4cb7545b7403bc305aa1b

**Comment by liach** [comment]
Merged in upstream https://bitbucket.org/mstrobel/procyon/commits/0cd559428189549843800617814627f04114235a

**Pull request closed without merging**
